### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Allenxuxu** [htdvisser/mqtt#1]
Hi, @htdvisser 

### What do you want instead?

Can you add some usage examples?

**Comment by htdvisser** [comment]
Hi @Allenxuxu, thank you for your interest in this project!

Adding some examples has been on my TODO list for a while, but I haven't really had much time to work on this project since I published it. I'll try to free up some time to help you get started.

**Comment by htdvisser** [comment]
Hey @Allenxuxu, I pushed some changes and added basic usage examples for both the client and server side. You can find them in the `example_*_test.go` files and on [Godoc](https://godoc.org/htdvisser.dev/mqtt). 

I hope these examples (and the other Godoc) are sufficient to help you get started.
